<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="X390" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-12-21T14:15:11 EST" time="15.909" errors="0">
  <testcase name="logoPresence" time="0.328" classname="ProjectOne.com.One.App"/>
  <testcase name="loginTest" time="4.69" classname="ProjectOne.com.One.App">
    <failure type="java.lang.AssertionError" message="expected [nopCommerce demo store123] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store123] but found [nopCommerce demo store. Login]
at ProjectOne.com.One.App.loginTest(App.java:64)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="registrationTest" time="0.006" classname="ProjectOne.com.One.App">
    <skipped/>
  </testcase> <!-- registrationTest -->
</testsuite> <!-- Test -->
