<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="X390" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-12-21T15:31:59 EST" time="15.973" errors="0">
  <testcase name="logoPresence" time="0.377" classname="allure.allureId.one"/>
  <testcase name="loginTest" time="4.254" classname="allure.allureId.one">
    <failure type="java.lang.AssertionError" message="expected [nopCommerce demo store123] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store123] but found [nopCommerce demo store. Login]
at allure.allureId.one.loginTest(one.java:66)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="registrationTest" time="0.006" classname="allure.allureId.one">
    <skipped/>
  </testcase> <!-- registrationTest -->
</testsuite> <!-- Test -->
